version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - platform-0.0.1-net
    environment:
      RABBIT_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@123
      RABBITMQ_VHOST: /
      RABBMITMQ_EXCHANGE: simple_email_exchange
      RABBITMQ_QUEUE: simple_email_queue

  simple_email_service:
    image: simple-email-service-dkr-img
    container_name: platform-ses
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - POSTGRES_HOST=postgres  # Adjust the hostname for PostgreSQL
      - POSTGRES_PASSWORD=postgres@123  # Replace with your PostgreSQL password
      - POSTGRES_USER=postgres  # Replace with your PostgreSQL username
      - POSTGRES_DB=platform_db  # Replace with your PostgreSQL database
      - POSTGRES_PORT=5432  # Replace with your PostgreSQL port
    networks:
      - platform-0.0.1-net

networks:
  platform-0.0.1-net:
    name: platform-0.0.1-net
    driver: bridge