version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: platform_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432  # Map container port 5432 to host port 5432
    networks:
      - platform-net

  rabbitmq:
    image: rabbitmq:3.9.7-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - platform-net
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@123
      RABBITMQ_VHOST: /
      RABBMITMQ_EXCHANGE: simple_email_exchange
      RABBITMQ_QUEUE: simple_email_queue


  simple_email_service:
    image: simple-email-service-dkr-img
    build:
      context: .
      dockerfile: ./Dockerfile

    depends_on:
      - postgres
      - rabbitmq
    environment:
      - POSTGRES_HOST=postgres  # Adjust the hostname for PostgreSQL
      - POSTGRES_PASSWORD=postgres@123  # Replace with your PostgreSQL password
      - POSTGRES_USER=postgres  # Replace with your PostgreSQL username
      - POSTGRES_DB=platform_db  # Replace with your PostgreSQL database
      - POSTGRES_PORT=5432  # Replace with your PostgreSQL port
    networks:
      - platform-net
    volumes:
      - ./app:/home/appuser/code/app

networks:
  platform-net:
    driver: bridge