service:
  name: simple-email-service
  title: "Simple Email Service"
  description: "Simple Email Service"
  contact:
    email: "rajeev.b@prowessenterprise.com"
  version: "1.0.0"

database:
  db_type: DbType.POSTGRES
  postgresdb_host: "postgres"
  postgresdb_username: "postgres"
logging:
  version: 1
  formatters:
    brief:
      format: "%(asctime)s %(name)s %(levelname)s : %(message)s"
    detailed:
      format: 'time="%(asctime)s" logger="%(name)s" level="%(levelname)s" file="%(filename)s" lineno=%(lineno)d function="%(funcName)s" %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: /tmp/simple-email-service-app.log
      backupCount: 3
  loggers:
    simple-email-service:
      level: DEBUG
      handlers:
        - console
        - file
      propagate: no

  root:
    level: WARNING
    handlers:
      - console
